spring:
  application:
    name: eshop-member

server:
  port: 8004

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

security:
  oauth2:
    resource:
      id: eshop-member
      user-info-uri: http://localhost:8002/auth/api/member
      prefer-token-info: false