spring:
  application:
    name: eshop-server

server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    # 一般情况下，Eureka服务端是不需要再注册自己的
    register-with-eureka: false
    # 是否从Eureka获取注册信息，缺省：true
    # 一般情况下，Eureka服务端是不需要的
    fetch-registry: false
    # 客户端拉取服务注册信息间隔，单位：秒，缺省：30
    registry-fetch-interval-seconds: 30
    # 是否启用客户端健康检查
    health-check.enabled: true
    eureka-service-url-poll-interval-seconds: 60
    # 连接Eureka服务器的超时时间，单位：秒，缺省：5
    eureka-server-connect-timeout-seconds: 5
    # 从Eureka服务器读取信息的超时时间，单位：秒，缺省：8
    eureka-server-read-timeout-seconds: 8
    # 获取实例时是否只保留状态为 UP 的实例，缺省：true
    filter-only-up-instances: true
    # Eureka服务端连接空闲时的关闭时间，单位：秒，缺省：30
    eureka-connection-idle-timeout-seconds: 30
    # 从Eureka客户端到所有Eureka服务端的连接总数，缺省：200
    eureka-server-total-connections: 200
    # 从Eureka客户端到每个Eureka服务主机的连接总数，缺省：50
    eureka-server-total-connections-per-host: 50
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

